#!/bin/bash -e
cd $(dirname $0)
sudo ./qemu-ifup tap0
sudo ./qemu-system-mipsel \
  -kernel ./openwrt-malta-le-vmlinux-initramfs.elf \
  -nographic -m 256  \
  -net nic -net tap,ifname=tap0,script=no,downscript=no
sudo ./qemu-ifup tap0
